# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - python==3.8.10
  - numpy
  - matplotlib
  - ipympl
  - pandas
  - scikit-learn
  - nbgitpuller
  - pykdtree
  - pyembree
  - scikit-build
  - pip
  - pip:
      - allensdk==2.13.6
      - caveclient==4.16.1
      - nglui==2.10.0
      - meshparty==1.16.4
