# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - python==3.8.10
  - numpy
  - matplotlib
  - ipympl
  - pandas
  - scikit-learn
  - nbgitpuller
  - pykdtree
  - pyembree
  - scikit-build
  - pip
  - pip:
      - allensdk==2.13.6
      - caveclient==4.16.2
      - nglui==2.10.1
      - meshparty==1.16.5
      - pcg-skel==0.3.0
      - git+https://github.com/AllenInstitute/em_coregistration.git@swdb
      - git+https://github.com/cajal/microns_phase3_nda.git
      - git+https://github.com/AllenInstitute/brain_observatory_utilities.git@v0.1.0
